// AUTO-GENERATED by scripts/check-amazon-stock.mjs on 2026-07-18 — do not edit.
// Best-effort availability read from public product pages; overlays the
// Amazon stock listings at runtime (see src/data/index.ts).
export interface AmazonStockEntry {
  inStock: boolean;
  price?: number;
  availabilityText: string;
  lastChecked: string;
}

export const amazonStock: Record<string, AmazonStockEntry> = {
  "B0DR7P7LXB": {
    "inStock": true,
    "price": 27.95,
    "availabilityText": "Only 20 left in stock - order soon.",
    "lastChecked": "2026-07-18"
  },
  "B0CDQKM2BN": {
    "inStock": true,
    "price": 22.6,
    "availabilityText": "Only 18 left in stock - order soon.",
    "lastChecked": "2026-07-18"
  },
  "B0FMZWB8RB": {
    "inStock": true,
    "availabilityText": "In Stock (inferred from buy box)",
    "lastChecked": "2026-07-18"
  },
  "B0GMXRYG9H": {
    "inStock": true,
    "availabilityText": "In Stock (inferred from buy box)",
    "lastChecked": "2026-07-18"
  },
  "B0GXQFYS66": {
    "inStock": false,
    "availabilityText": "Listing removed from Amazon",
    "lastChecked": "2026-07-18"
  }
};
